# Generated by Django 3.1.7 on 2021-06-14 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=datetime.datetime(2021, 6, 14, 7, 32, 48, 701688, tzinfo=utc))),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
