# Generated by Django 3.1.7 on 2021-06-14 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 17, 8, 23, 243823, tzinfo=utc)),
        ),
    ]
