# Generated by Django 3.1.7 on 2021-06-14 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0002_auto_20210614_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 17, 32, 25, 209051, tzinfo=utc)),
        ),
    ]
