# Generated by Django 3.1.7 on 2021-06-14 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0003_auto_20210614_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 17, 34, 20, 513200, tzinfo=utc)),
        ),
    ]
