# Generated by Django 3.1.7 on 2021-06-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0005_auto_20210614_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(),
        ),
    ]
